# Generated by Django 5.1.3 on 2024-11-08 12:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpyCat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=258)),
                ('years_of_exp', models.IntegerField()),
                ('breed', models.CharField(max_length=128)),
                ('salary', models.DecimalField(decimal_places=5, max_digits=10)),
            ],
        ),
    ]
